const MIN_TYPE_PRICE = {
  bungalow: 0,
  flat: 1000,
  hotel: 3000,
  house: 5000,
  palace: 10000,
};

const MIN_TITLE_LENGTH = 30;
const MAX_TITLE_LENGTH = 100;

const DEFAULT_LOCATION = {

  lat: 35.68770,
  lng: 139.75433,

};

const ZOOM = 12;
const COUNT = 10;

const MAIN_MARKER_ICON_URL = 'img/main-pin.svg';
const MAIN_MARKER_ICON_SIZES = [52, 52];
const MAIN_MARKER_ICON_ANCHORS = [26, 52];

const MARKER_ICON_URL = 'img/pin.svg';
const MARKER_ICON_SIZES = [40, 40];
const MARKER_ICON_ANCHORS = [20, 40];

const FILE_TYPES = ['gif', 'jpg', 'jpeg', 'png'];

export {MIN_TITLE_LENGTH, MAX_TITLE_LENGTH, MIN_TYPE_PRICE, DEFAULT_LOCATION, ZOOM, COUNT, FILE_TYPES, MAIN_MARKER_ICON_URL, MAIN_MARKER_ICON_SIZES, MAIN_MARKER_ICON_ANCHORS, MARKER_ICON_URL, MARKER_ICON_SIZES, MARKER_ICON_ANCHORS};
